### ISSUE TITLE
Add elf to uf2 converter script

### ISSUE THREAD

**Issue by marnovandermaas** [lowRISC/sonata-software#39]
So that this instruction works:
https://github.com/lowRISC/sonata-software/blob/5a778c7aed78794faa53cc7109140b357d8f3571/doc/exploring-cheriot-rtos.md?plain=1#L48

**Comment by nbdd0121** [comment]
The script is available in sonata-system util/elf-to-uf2.sh

**Comment by marnovandermaas** [comment]
Aha, but we only ask people to clone the sonata-software repository in this book.

**Comment by marnovandermaas** [comment]
Oh is there a way for Nix to pull this in from sonata-system and put it in the path? That way we don't have to copy it across.
