### ISSUE TITLE
Various issues in dev container

### ISSUE THREAD

**Issue by PhilDay-CT** [lowRISC/sonata-software#59]
I was trying to use the dev container with VS Code on Linux, and ran into a number of issues:

The default term profile (nix-devshell) won't open, but I could open a bash terminal

Once in there I could only run "nix develop" as root
```
sudo /nix/var/nix/profiles/default/bin/nix develop
``` 
which gave a bunch of security warnings, but I figured these were probably OK as I'm in a container

I then also had to run xmake with the --root option
```
xmake --root -P examples
```

which did create some .uf2 files that I could then copy to the Sonata mount, but it didn't for example build a uf2 for snake (and I couldn't find any instructions other that the make for "all" the examples.

Is the dev container supported (although the files are there  which makes VS Code ask if I want to use it) I couldn't find any mention of it in the docs ?

**Comment by GregAC** [comment]
Hi @PhilDay-CT 

The devcontainer is unsupported. It was quickly added before our first hackathon as a backup option for people who had trouble getting the nix environment running. We should have removed it, I'll do that now.
